### ISSUE TITLE
Can't launch the service

### ISSUE THREAD

**Issue by dtitov** [CSCfi/oidc-client#14]
#### Describe the bug
```
% start_oidc_client                                     
zsh: abort      start_oidc_client
```

```
% python3 -m oidc_client.app
zsh: abort      python3 -m oidc_client.app
```

#### To Reproduce
Steps to reproduce the behaviour:
1. Install the tool by following README instructions.
2. Try to launch it.
3. See error

#### Expected behavior
The server is started.

#### Additional context
I guess the problem might be with `zsh`, because on `bash` it works (on another machine though). But it's just an assumption.

**Comment by dtitov** [comment]
This "solution" helped: https://github.com/Homebrew/homebrew-core/issues/44996#issuecomment-540674866

Apparently, `asn1crypto` library somehow breaks everything. After I uninstalled it, `oidc-client` launches successfully.

**Comment by blankdots** [comment]
Will close for now, as the issue was not with our code.
